spring:
  datasource:
    driverName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/element-admin-web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  file:
    path: /opt/webs/jar/logs
  level:
    root: info
    com.hongtech.admin: info
minio:
  server: http://101.43.151.105:9000
  accessKey: admin
  secretKey: password

zip:
  filepath: D:\\